function S=S(h,k,l)

S=1+...
  exp(pi*1i*(h+k))+...
  exp(pi*1i*(h+l))+...
  exp(pi*1i*(l+k))+...
  exp(pi*1i*(h+k+l)/2)+...
  exp(pi*1i*(3*h+3*l+k)/2)+...
  exp(pi*1i*(h+3*k+3*l)/2)+...
  exp(pi*1i*(3*h+3*k+l)/2);
S=abs(S);
end