pause(1)
display('¡Victoria!')
pause(1)
display('Acabas de dejar sin marido a un montón de mujeres enemigas')
display('¡Eso significa más sexo para los tuyos!')
display('Enhorabuena ;)')
pause(2)
disp('---')
disp('Lo has conseguido en')
disp(' ')
disp(h)
disp('intentos.')
pause(1)
disp('---')
disp('Tiempo')
disp(' ')
disp(t)
disp('---')
pause(1)